### ISSUE TITLE
老哥有没有兴趣看一下我的同类实现

### ISSUE THREAD

**Issue by fumeboy** [CCChieh/ginHelper#1]
地址是 https://github.com/fumeboy/nji

**Comment by CCChieh** [comment]
看了下你的项目，这应该是要做一个类似gin的框架，而我想要做的是对gin做一点改进，方便的引入一些重复的api，起初的目标是通过这种方式快速的引入类似swagger的api文档调试工具，不过最近发现似乎无法做到不修改gin的方式下实现相关的功能，如果可以，希望你的框架以后可以实现类似spring boot中便捷的引入swagger的方式，而不是现在的通过注释来实现相关功能

**Comment by fumeboy** [comment]
啊，意思是没有写说明文档吗，这个实在对不起，主要是觉得 readme 展示项目功能已经足够了。要给go项目增加一个功能是不可能和原项目解耦合的，你必须将gin拆开来把它变成自己的，只要接口一致，原先gin的插件也是一样使用的
